package rabbitmqamqp

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("Entities", func() {
	Describe("AutoGeneratedQueueSpecification", func() {
		It("should generate a unique name consistently", func() {
			queue := &AutoGeneratedQueueSpecification{}
			generatedName := queue.name()
			Expect(queue.name()).To(Equal(generatedName), "same instance should generate the same name")

			anotherQueue := &AutoGeneratedQueueSpecification{}
			anotherGeneratedName := anotherQueue.name()
			Expect(anotherQueue.name()).To(Equal(anotherGeneratedName), "same instance should generate the same name")

			Expect(generatedName).ToNot(Equal(anotherGeneratedName), "different instances should generate different names")
		})
	})
})
