package rabbitmqamqp

import (
	"fmt"
	"time"
)

// QuorumQueueDelayedRetryType controls the x-delayed-retry-type queue argument for quorum queues.
// This feature requires RabbitMQ 4.3 or later.
type QuorumQueueDelayedRetryType string

const (
	// QuorumQueueDelayedRetryDisabled disables delayed retry redelivery (default).
	QuorumQueueDelayedRetryDisabled QuorumQueueDelayedRetryType = "disabled"

	// QuorumQueueDelayedRetryAll delays all returned messages, regardless of whether the
	// delivery-count was incremented.
	QuorumQueueDelayedRetryAll QuorumQueueDelayedRetryType = "all"

	// QuorumQueueDelayedRetryFailed delays only messages whose delivery-count was incremented.
	// This is triggered by RequeueWithAnnotationsAndDeliveryFailed(ctx, annotations, true)
	// or DelayRetry(delay, true).
	QuorumQueueDelayedRetryFailed QuorumQueueDelayedRetryType = "failed"

	// QuorumQueueDelayedRetryReturned delays only messages whose x-acquired-count was incremented.
	// This is triggered by Requeue(), RequeueWithAnnotations(), or
	// RequeueWithAnnotationsAndDeliveryFailed(ctx, annotations, false) / DelayRetry(delay, false).
	QuorumQueueDelayedRetryReturned QuorumQueueDelayedRetryType = "returned"
)

type iEntityIdentifier interface {
	Id() string
}

// TQueueType identifies the RabbitMQ queue type sent in the x-queue-type argument.
type TQueueType string

const (
	// Quorum is the quorum queue type: a durable, replicated queue backed by the Raft consensus algorithm.
	Quorum TQueueType = "quorum"
	// Classic is the traditional RabbitMQ queue type.
	Classic TQueueType = "classic"
	// Stream is the append-only log queue type, suited for high-throughput and replay scenarios.
	Stream TQueueType = "stream"
	// Jms is the JMS queue type available on Tanzu RabbitMQ.
	Jms TQueueType = "jms"
	// Delayed is the delayed-delivery queue type available on Tanzu RabbitMQ 4.3 or later.
	Delayed TQueueType = "delayed"
)

/*
IQueueSpecification represents the specification of a queue.
The implementation of the queue specification can be used to declare a queue with the specified properties and arguments.
The client provides multiple implementations of the queue specification for different use cases,
such as DefaultQueueSpecification, QuorumQueueSpecification, ClassicQueueSpecification, JMSQueueSpecification,
DelayedQueueSpecification, AutoGeneratedQueueSpecification, and CustomQueueSpecification.
The client implementations are helpers that cover the most common use cases, but you can implement your own queue
specification by implementing the IQueueSpecification interface.
*/
type IQueueSpecification interface {
	name() string
	isAutoDelete() bool
	isExclusive() bool
	queueType() TQueueType
	buildArguments() map[string]any
	validate(featuresAvailable *featuresAvailable) error
}

// IOverflowStrategy defines the behaviour RabbitMQ applies when a queue reaches its maximum length.
// Set via the x-overflow queue argument.
type IOverflowStrategy interface {
	overflowStrategy() string
}

// DropHeadOverflowStrategy drops the oldest (head) messages to make room for new ones.
// Corresponds to the x-overflow value "drop-head".
type DropHeadOverflowStrategy struct {
}

func (d *DropHeadOverflowStrategy) overflowStrategy() string {
	return "drop-head"
}

// RejectPublishOverflowStrategy rejects newly published messages when the queue is full.
// Corresponds to the x-overflow value "reject-publish".
type RejectPublishOverflowStrategy struct {
}

func (r *RejectPublishOverflowStrategy) overflowStrategy() string {
	return "reject-publish"
}

// RejectPublishDlxOverflowStrategy rejects newly published messages and routes them to the
// configured dead-letter exchange (DLX) when the queue is full.
// Corresponds to the x-overflow value "reject-publish-dlx".
type RejectPublishDlxOverflowStrategy struct {
}

func (r *RejectPublishDlxOverflowStrategy) overflowStrategy() string {
	return "reject-publish-dlx"
}

// ILeaderLocator controls which cluster node is selected as the queue leader.
// Set via the x-queue-leader-locator queue argument.
type ILeaderLocator interface {
	leaderLocator() string
}

// BalancedLeaderLocator places the queue leader on a randomly chosen cluster node,
// distributing leaders evenly across the cluster.
// Corresponds to the x-queue-leader-locator value "random".
type BalancedLeaderLocator struct {
}

func (r *BalancedLeaderLocator) leaderLocator() string {
	return "random"
}

// ClientLocalLeaderLocator places the queue leader on the node to which the declaring
// client is connected, minimising cross-node traffic for that client.
// Corresponds to the x-queue-leader-locator value "client-local".
type ClientLocalLeaderLocator struct {
}

func (r *ClientLocalLeaderLocator) leaderLocator() string {
	return "client-local"
}

// DefaultQueueSpecification represents the specification of the default queue.
// It is used when the queue type is not specified.
// The queue type is determined by the server based on the arguments provided per virtual host configuration.
type DefaultQueueSpecification struct {
	// Name is the queue name. Must be unique within the virtual host.
	Name string
	// IsAutoDelete causes the queue to be deleted automatically when the last consumer disconnects.
	IsAutoDelete bool
	// IsExclusive restricts the queue to the connection that declared it and deletes it on disconnection.
	IsExclusive bool
	// AutoExpire is the time in milliseconds after which the queue is deleted if unused (x-expires).
	AutoExpire int64
	// MessageTTL is the default time in milliseconds a message is retained before being discarded (x-message-ttl).
	MessageTTL int64
	// OverflowStrategy controls what happens when the queue reaches MaxLength or MaxLengthBytes (x-overflow).
	OverflowStrategy IOverflowStrategy
	// SingleActiveConsumer ensures only one consumer receives messages at a time (x-single-active-consumer).
	SingleActiveConsumer bool
	// DeadLetterExchange is the exchange to which dead-lettered messages are routed (x-dead-letter-exchange).
	DeadLetterExchange string
	// DeadLetterRoutingKey overrides the routing key used when dead-lettering messages (x-dead-letter-routing-key).
	DeadLetterRoutingKey string
	// MaxLength is the maximum number of messages the queue holds before the overflow strategy is applied (x-max-length).
	MaxLength int64
	// MaxLengthBytes is the maximum total size in bytes of messages in the queue (x-max-length-bytes).
	MaxLengthBytes int64
	// MaxPriority enables priority queuing with the given number of priority levels (x-max-priority).
	MaxPriority int64
	// LeaderLocator controls which cluster node is chosen as the queue leader (x-queue-leader-locator).
	LeaderLocator ILeaderLocator
	// QuorumInitialGroupSize is the initial replication factor for quorum queues (x-quorum-initial-group-size).
	QuorumInitialGroupSize int
	// Arguments holds additional queue arguments passed directly to the broker.
	Arguments map[string]any
}

func (q *DefaultQueueSpecification) name() string {
	return q.Name
}

func (q *DefaultQueueSpecification) isAutoDelete() bool {
	return q.IsAutoDelete
}

func (q *DefaultQueueSpecification) isExclusive() bool {
	return q.IsExclusive
}

func (q *DefaultQueueSpecification) queueType() TQueueType {
	return ""
}

func (q *DefaultQueueSpecification) buildArguments() map[string]any {
	result := q.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if q.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = q.MaxLengthBytes
	}

	if len(q.DeadLetterExchange) != 0 {
		result["x-dead-letter-exchange"] = q.DeadLetterExchange
	}

	if len(q.DeadLetterRoutingKey) != 0 {
		result["x-dead-letter-routing-key"] = q.DeadLetterRoutingKey
	}

	if q.AutoExpire != 0 {
		result["x-expires"] = q.AutoExpire
	}

	if q.MessageTTL != 0 {
		result["x-message-ttl"] = q.MessageTTL
	}

	if q.OverflowStrategy != nil {
		result["x-overflow"] = q.OverflowStrategy.overflowStrategy()
	}

	if q.SingleActiveConsumer {
		result["x-single-active-consumer"] = true
	}

	if q.MaxLength != 0 {
		result["x-max-length"] = q.MaxLength
	}

	if q.MaxPriority != 0 {
		result["x-max-priority"] = q.MaxPriority
	}

	if q.LeaderLocator != nil {
		result["x-queue-leader-locator"] = q.LeaderLocator.leaderLocator()
	}

	if q.QuorumInitialGroupSize != 0 {
		result["x-quorum-initial-group-size"] = q.QuorumInitialGroupSize
	}

	return result

}

func (q *DefaultQueueSpecification) validate(*featuresAvailable) error {
	return nil
}

// QuorumQueueSpecification represents the specification of a quorum queue.
// Quorum queues are durable, replicated queues backed by the Raft consensus algorithm.
// Auto-delete and exclusive options are not supported and are always false.
type QuorumQueueSpecification struct {
	// Name is the queue name. Must be unique within the virtual host.
	Name string
	// AutoExpire is the time in milliseconds after which the queue is deleted if unused (x-expires).
	AutoExpire int64
	// MessageTTL is the default time in milliseconds a message is retained before being discarded (x-message-ttl).
	MessageTTL int64
	// OverflowStrategy controls what happens when the queue reaches MaxLength or MaxLengthBytes (x-overflow).
	OverflowStrategy IOverflowStrategy
	// SingleActiveConsumer ensures only one consumer receives messages at a time (x-single-active-consumer).
	SingleActiveConsumer bool
	// DeadLetterExchange is the exchange to which dead-lettered messages are routed (x-dead-letter-exchange).
	DeadLetterExchange string
	// DeadLetterRoutingKey overrides the routing key used when dead-lettering messages (x-dead-letter-routing-key).
	DeadLetterRoutingKey string
	// MaxLength is the maximum number of messages the queue holds before the overflow strategy is applied (x-max-length).
	MaxLength int64
	// MaxLengthBytes is the maximum total size in bytes of messages in the queue (x-max-length-bytes).
	MaxLengthBytes int64
	// DeliveryLimit is the maximum number of times a message is delivered before it is dead-lettered (x-delivery-limit).
	DeliveryLimit int64
	// TargetClusterSize is the desired number of replicas for the queue (x-quorum-target-group-size).
	TargetClusterSize int64
	// LeaderLocator controls which cluster node is chosen as the queue leader (x-queue-leader-locator).
	LeaderLocator ILeaderLocator
	// QuorumInitialGroupSize is the initial replication factor when the queue is first declared (x-quorum-initial-group-size).
	QuorumInitialGroupSize int
	// DelayedRetryType enables linear back-off redelivery on the quorum queue.
	// Requires RabbitMQ 4.3 or later. Maps to the x-delayed-retry-type queue argument.
	DelayedRetryType QuorumQueueDelayedRetryType
	// DelayedRetryMin is the minimum delay before a message is redelivered.
	// Requires RabbitMQ 4.3 or later. Maps to the x-delayed-retry-min queue argument (milliseconds).
	DelayedRetryMin time.Duration
	// DelayedRetryMax is the maximum delay before a message is redelivered.
	// Requires RabbitMQ 4.3 or later. Maps to the x-delayed-retry-max queue argument (milliseconds).
	DelayedRetryMax time.Duration
	// Arguments holds additional queue arguments passed directly to the broker.
	Arguments map[string]any
}

func (q *QuorumQueueSpecification) name() string {
	return q.Name
}

func (q *QuorumQueueSpecification) isAutoDelete() bool {
	return false
}

func (q *QuorumQueueSpecification) isExclusive() bool {
	return false
}

func (q *QuorumQueueSpecification) queueType() TQueueType {
	return Quorum
}

func (q *QuorumQueueSpecification) buildArguments() map[string]any {
	result := q.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if q.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = q.MaxLengthBytes
	}

	if len(q.DeadLetterExchange) != 0 {
		result["x-dead-letter-exchange"] = q.DeadLetterExchange
	}

	if len(q.DeadLetterRoutingKey) != 0 {
		result["x-dead-letter-routing-key"] = q.DeadLetterRoutingKey
	}

	if q.AutoExpire != 0 {
		result["x-expires"] = q.AutoExpire
	}

	if q.MessageTTL != 0 {
		result["x-message-ttl"] = q.MessageTTL
	}

	if q.OverflowStrategy != nil {
		result["x-overflow"] = q.OverflowStrategy.overflowStrategy()
	}

	if q.SingleActiveConsumer {
		result["x-single-active-consumer"] = true
	}

	if q.MaxLength != 0 {
		result["x-max-length"] = q.MaxLength
	}

	if q.DeliveryLimit != 0 {
		result["x-delivery-limit"] = q.DeliveryLimit
	}

	if q.TargetClusterSize != 0 {
		result["x-quorum-target-group-size"] = q.TargetClusterSize
	}

	if q.LeaderLocator != nil {
		result["x-queue-leader-locator"] = q.LeaderLocator.leaderLocator()
	}

	if q.QuorumInitialGroupSize != 0 {
		result["x-quorum-initial-group-size"] = q.QuorumInitialGroupSize
	}

	if len(q.DelayedRetryType) != 0 {
		result["x-delayed-retry-type"] = string(q.DelayedRetryType)
	}

	if q.DelayedRetryMin != 0 {
		result["x-delayed-retry-min"] = q.DelayedRetryMin.Milliseconds()
	}

	if q.DelayedRetryMax != 0 {
		result["x-delayed-retry-max"] = q.DelayedRetryMax.Milliseconds()
	}

	result["x-queue-type"] = string(q.queueType())
	return result
}

func (q *QuorumQueueSpecification) validate(f *featuresAvailable) error {
	if f != nil && (len(q.DelayedRetryType) != 0 || q.DelayedRetryMin != 0 || q.DelayedRetryMax != 0) {
		if !f.is43rMore {
			return fmt.Errorf("QuorumQueueSpecification delayed retry fields require RabbitMQ 4.3 or later")
		}
	}
	return nil
}

// ClassicQueueSpecification represents the specification of a classic queue.
// Classic queues are the traditional RabbitMQ queue type.
type ClassicQueueSpecification struct {
	// Name is the queue name. Must be unique within the virtual host.
	Name string
	// IsAutoDelete causes the queue to be deleted automatically when the last consumer disconnects.
	IsAutoDelete bool
	// IsExclusive restricts the queue to the connection that declared it and deletes it on disconnection.
	IsExclusive bool
	// AutoExpire is the time in milliseconds after which the queue is deleted if unused (x-expires).
	AutoExpire int64
	// MessageTTL is the default time in milliseconds a message is retained before being discarded (x-message-ttl).
	MessageTTL int64
	// OverflowStrategy controls what happens when the queue reaches MaxLength or MaxLengthBytes (x-overflow).
	OverflowStrategy IOverflowStrategy
	// SingleActiveConsumer ensures only one consumer receives messages at a time (x-single-active-consumer).
	SingleActiveConsumer bool
	// DeadLetterExchange is the exchange to which dead-lettered messages are routed (x-dead-letter-exchange).
	DeadLetterExchange string
	// DeadLetterRoutingKey overrides the routing key used when dead-lettering messages (x-dead-letter-routing-key).
	DeadLetterRoutingKey string
	// MaxLength is the maximum number of messages the queue holds before the overflow strategy is applied (x-max-length).
	MaxLength int64
	// MaxLengthBytes is the maximum total size in bytes of messages in the queue (x-max-length-bytes).
	MaxLengthBytes int64
	// MaxPriority enables priority queuing with the given number of priority levels (x-max-priority).
	MaxPriority int64
	// LeaderLocator controls which cluster node is chosen as the queue leader (x-queue-leader-locator).
	LeaderLocator ILeaderLocator
	// Arguments holds additional queue arguments passed directly to the broker.
	Arguments map[string]any
}

func (q *ClassicQueueSpecification) name() string {
	return q.Name
}

func (q *ClassicQueueSpecification) isAutoDelete() bool {
	return q.IsAutoDelete
}

func (q *ClassicQueueSpecification) isExclusive() bool {
	return q.IsExclusive
}

func (q *ClassicQueueSpecification) queueType() TQueueType {
	return Classic
}

func (q *ClassicQueueSpecification) buildArguments() map[string]any {
	result := q.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if q.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = q.MaxLengthBytes
	}

	if len(q.DeadLetterExchange) != 0 {
		result["x-dead-letter-exchange"] = q.DeadLetterExchange
	}

	if len(q.DeadLetterRoutingKey) != 0 {
		result["x-dead-letter-routing-key"] = q.DeadLetterRoutingKey
	}

	if q.AutoExpire != 0 {
		result["x-expires"] = q.AutoExpire
	}

	if q.MessageTTL != 0 {
		result["x-message-ttl"] = q.MessageTTL
	}

	if q.OverflowStrategy != nil {
		result["x-overflow"] = q.OverflowStrategy.overflowStrategy()
	}

	if q.SingleActiveConsumer {
		result["x-single-active-consumer"] = true
	}

	if q.MaxLength != 0 {
		result["x-max-length"] = q.MaxLength
	}

	if q.MaxPriority != 0 {
		result["x-max-priority"] = q.MaxPriority
	}

	if q.LeaderLocator != nil {
		result["x-queue-leader-locator"] = q.LeaderLocator.leaderLocator()
	}

	result["x-queue-type"] = string(q.queueType())

	return result
}

func (q *ClassicQueueSpecification) validate(*featuresAvailable) error {
	return nil
}

// AutoGeneratedQueueSpecification represents a classic queue with a client-generated name.
// It is useful in contexts like RPC or any scenario that requires a temporary, anonymous queue.
// If you need temporary queues, have a look to [DirectReplyTo] feature
type AutoGeneratedQueueSpecification struct {
	genName string
	// IsAutoDelete causes the queue to be deleted automatically when the last consumer disconnects.
	IsAutoDelete bool
	// IsExclusive restricts the queue to the connection that declared it and deletes it on disconnection.
	IsExclusive bool
	// MaxLength is the maximum number of messages the queue holds before the overflow strategy is applied (x-max-length).
	MaxLength int64
	// MaxLengthBytes is the maximum total size in bytes of messages in the queue (x-max-length-bytes).
	MaxLengthBytes int64
	// Arguments holds additional queue arguments passed directly to the broker.
	Arguments map[string]any
}

func (a *AutoGeneratedQueueSpecification) name() string {
	if a.genName == "" {
		a.genName = generateNameWithDefaultPrefix()
	}
	return a.genName
}

func (a *AutoGeneratedQueueSpecification) isAutoDelete() bool {
	return a.IsAutoDelete
}

func (a *AutoGeneratedQueueSpecification) isExclusive() bool {
	return a.IsExclusive
}

func (a *AutoGeneratedQueueSpecification) queueType() TQueueType {
	return Classic
}

func (a *AutoGeneratedQueueSpecification) buildArguments() map[string]any {
	result := a.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if a.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = a.MaxLengthBytes
	}

	if a.MaxLength != 0 {
		result["x-max-length"] = a.MaxLength
	}

	result["x-queue-type"] = string(a.queueType())

	return result
}

func (a *AutoGeneratedQueueSpecification) validate(*featuresAvailable) error {
	return nil
}

// StreamQueueSpecification represents the specification of a stream queue.
// Stream queues are append-only logs suited for high-throughput and message-replay scenarios.
// Auto-delete and exclusive options are not supported and are always false.
type StreamQueueSpecification struct {
	// Name is the queue name. Must be unique within the virtual host.
	Name string
	// MaxLengthBytes is the maximum total size of the stream in bytes. Older segments are deleted when exceeded (x-max-length-bytes).
	MaxLengthBytes int64
	// InitialClusterSize is the number of replicas created when the stream is first declared (x-stream-initial-cluster-size).
	InitialClusterSize int
	// MaxAge is the maximum retention period for stream messages. Older messages are deleted (x-max-age).
	MaxAge time.Duration
	// SegmentSize is the maximum size in bytes of each stream segment file (x-stream-max-segment-size-bytes).
	SegmentSize int64
	// FilterSizeBytes is the size in bytes of the Bloom filter used for stream filtering (x-stream-filter-size-bytes).
	FilterSizeBytes int64
	// Arguments holds additional queue arguments passed directly to the broker.
	Arguments map[string]any
}

func (s *StreamQueueSpecification) name() string {
	return s.Name
}

func (s *StreamQueueSpecification) isAutoDelete() bool {
	return false
}

func (s *StreamQueueSpecification) isExclusive() bool {
	return false
}

func (s *StreamQueueSpecification) queueType() TQueueType {
	return Stream
}

func (s *StreamQueueSpecification) buildArguments() map[string]any {
	result := s.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if s.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = s.MaxLengthBytes
	}

	if s.InitialClusterSize != 0 {
		result["x-stream-initial-cluster-size"] = s.InitialClusterSize
	}

	if s.MaxAge != 0 {
		result["x-max-age"] = durationToMaxAge(s.MaxAge)
	}

	if s.SegmentSize != 0 {
		result["x-stream-max-segment-size-bytes"] = s.SegmentSize
	}

	if s.FilterSizeBytes != 0 {
		result["x-stream-filter-size-bytes"] = s.FilterSizeBytes
	}

	result["x-queue-type"] = string(s.queueType())

	return result
}

func (s *StreamQueueSpecification) validate(*featuresAvailable) error {
	return nil
}

// JMSQueueSpecification represents the specification of a JMS queue (x-queue-type: jms).
// JMS queues are only available on Tanzu RabbitMQ 4.3 or later.
// Auto-delete and exclusive options are not supported and are always false.
type JMSQueueSpecification struct {
	// Name is the queue name. Must be unique within the virtual host.
	Name string
	// Arguments holds additional queue arguments passed directly to the broker.
	Arguments map[string]any
	// AutoExpire is the time in milliseconds after which the queue is deleted if unused (x-expires).
	AutoExpire int64
	// MessageTTL is the default time in milliseconds a message is retained before being discarded (x-message-ttl).
	MessageTTL int64
	// OverflowStrategy controls what happens when the queue reaches MaxLength or MaxLengthBytes (x-overflow).
	OverflowStrategy IOverflowStrategy
	// DeadLetterExchange is the exchange to which dead-lettered messages are routed (x-dead-letter-exchange).
	DeadLetterExchange string
	// DeadLetterRoutingKey overrides the routing key used when dead-lettering messages (x-dead-letter-routing-key).
	DeadLetterRoutingKey string
	// MaxLength is the maximum number of messages the queue holds before the overflow strategy is applied (x-max-length).
	MaxLength int64
	// MaxLengthBytes is the maximum total size in bytes of messages in the queue (x-max-length-bytes).
	MaxLengthBytes int64
	// DeliveryLimit is the maximum number of times a message is delivered before it is dead-lettered (x-delivery-limit).
	DeliveryLimit int64
	// LeaderLocator controls which cluster node is chosen as the queue leader (x-queue-leader-locator).
	LeaderLocator ILeaderLocator
	// InitialClusterSize is the initial replication factor when the queue is first declared (x-quorum-initial-group-size).
	InitialClusterSize int
	// SelectorFields lists the JMS message property names used for server-side selector evaluation.
	SelectorFields []string
}

func (j *JMSQueueSpecification) name() string {
	return j.Name
}

func (j *JMSQueueSpecification) isAutoDelete() bool {
	return false
}

func (j *JMSQueueSpecification) isExclusive() bool {
	return false
}

func (j *JMSQueueSpecification) queueType() TQueueType {
	return Jms
}

func (j *JMSQueueSpecification) buildArguments() map[string]any {
	result := j.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if j.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = j.MaxLengthBytes
	}

	if len(j.DeadLetterExchange) != 0 {
		result["x-dead-letter-exchange"] = j.DeadLetterExchange
	}

	if len(j.DeadLetterRoutingKey) != 0 {
		result["x-dead-letter-routing-key"] = j.DeadLetterRoutingKey
	}

	if j.AutoExpire != 0 {
		result["x-expires"] = j.AutoExpire
	}

	if j.MessageTTL != 0 {
		result["x-message-ttl"] = j.MessageTTL
	}

	if j.OverflowStrategy != nil {
		result["x-overflow"] = j.OverflowStrategy.overflowStrategy()
	}

	result["x-queue-type"] = string(j.queueType())

	return result
}

func (j *JMSQueueSpecification) validate(f *featuresAvailable) error {
	// valid only if it is tanzu
	if f.isTanzu && f.is43rMore {
		return nil
	}
	// error not support for open source RabbitMQ

	return fmt.Errorf("JMSQueueSpecification is only supported on Tanzu RabbitMQ 4.3 or later")

}

// Default values applied to the automatic-shovel arguments of a DelayedQueueSpecification
// when ShovelDestination is set but the individual shovel fields are left at their zero values.
// See the Tanzu RabbitMQ delayed queue documentation for details.
const (
	// DefaultDelayedShovelDestinationURI is the AMQP URI of the shovel destination broker (x-shovel-destination-uri).
	DefaultDelayedShovelDestinationURI = "amqp://"
	// DefaultDelayedShovelProtocol is the messaging protocol used by the shovel (x-shovel-protocol).
	DefaultDelayedShovelProtocol = "amqp091"
	// DefaultDelayedShovelPrefetch is the number of messages the shovel fetches per round-trip (x-shovel-prefetch-count).
	DefaultDelayedShovelPrefetch = 50
	// DefaultDelayedShovelAcknowledgement is the acknowledgement mode used by the shovel (x-shovel-ack-mode).
	DefaultDelayedShovelAcknowledgement = "on-confirm"
)

// DelayedQueueSpecification represents the specification of a delayed queue (x-queue-type: delayed).
// Delayed queues are only available on Tanzu RabbitMQ 4.x or later.
// Queues are declared as durable; auto-delete defaults to false unless IsAutoDelete is set.
type DelayedQueueSpecification struct {
	// Name is the queue name. Must be unique within the virtual host.
	Name string
	// IsAutoDelete causes the queue to be deleted automatically when the last consumer disconnects.
	IsAutoDelete bool
	// IsExclusive restricts the queue to the connection that declared it and deletes it on disconnection.
	IsExclusive bool
	// Arguments holds additional queue arguments passed directly to the broker.
	Arguments map[string]any
	// AutoExpire is the time in milliseconds after which the queue is deleted if unused (x-expires).
	AutoExpire int64
	// MessageTTL is the default time in milliseconds a message is retained before being discarded (x-message-ttl).
	MessageTTL int64
	// OverflowStrategy controls what happens when the queue reaches MaxLength or MaxLengthBytes (x-overflow).
	OverflowStrategy IOverflowStrategy
	// SingleActiveConsumer ensures only one consumer receives messages at a time (x-single-active-consumer).
	SingleActiveConsumer bool
	// DeadLetterExchange is the exchange to which dead-lettered messages are routed (x-dead-letter-exchange).
	DeadLetterExchange string
	// DeadLetterRoutingKey overrides the routing key used when dead-lettering messages (x-dead-letter-routing-key).
	DeadLetterRoutingKey string
	// MaxLength is the maximum number of messages the queue holds before the overflow strategy is applied (x-max-length).
	MaxLength int64
	// MaxLengthBytes is the maximum total size in bytes of messages in the queue (x-max-length-bytes).
	MaxLengthBytes int64
	// DeliveryLimit is the maximum number of times a message is delivered before it is dead-lettered (x-delivery-limit).
	DeliveryLimit int64
	// InitialClusterSize is the initial replication factor when the queue is first declared (x-quorum-initial-group-size).
	InitialClusterSize int
	// TargetClusterSize is the desired number of replicas for the queue (x-quorum-target-group-size).
	TargetClusterSize int64
	// DeadLetterStrategy controls how dead-lettered messages are handled (x-dead-letter-strategy).
	DeadLetterStrategy string
	// LeaderLocator controls which cluster node is chosen as the queue leader (x-queue-leader-locator).
	LeaderLocator ILeaderLocator

	// ShovelDestination is the name of the destination queue used by the automatic shovel (x-shovel-destination).
	// When set, the remaining Shovel* fields configure the shovel. Defaults are applied for any zero-value field.
	ShovelDestination string
	// ShovelDestinationRoutingKey is the routing key used by the shovel when forwarding messages (x-shovel-destination-key).
	ShovelDestinationRoutingKey string
	// ShovelDestinationURI is the AMQP URI of the broker the shovel forwards messages to (x-shovel-destination-uri).
	// Defaults to DefaultDelayedShovelDestinationURI when empty.
	ShovelDestinationURI string
	// ShovelProtocol is the messaging protocol used by the shovel (x-shovel-protocol).
	// Defaults to DefaultDelayedShovelProtocol when empty.
	ShovelProtocol string
	// ShovelPrefetch is the number of messages the shovel fetches per round-trip (x-shovel-prefetch-count).
	// Defaults to DefaultDelayedShovelPrefetch when zero.
	ShovelPrefetch int
	// ShovelAcknowledgement is the acknowledgement mode used by the shovel (x-shovel-ack-mode).
	// Defaults to DefaultDelayedShovelAcknowledgement when empty.
	ShovelAcknowledgement string
}

func (d *DelayedQueueSpecification) name() string {
	return d.Name
}

func (d *DelayedQueueSpecification) isAutoDelete() bool {
	return d.IsAutoDelete
}

func (d *DelayedQueueSpecification) isExclusive() bool {
	return d.IsExclusive
}

func (d *DelayedQueueSpecification) queueType() TQueueType {
	return Delayed
}

func (d *DelayedQueueSpecification) buildArguments() map[string]any {
	result := d.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if d.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = d.MaxLengthBytes
	}

	if len(d.DeadLetterExchange) != 0 {
		result["x-dead-letter-exchange"] = d.DeadLetterExchange
	}

	if len(d.DeadLetterRoutingKey) != 0 {
		result["x-dead-letter-routing-key"] = d.DeadLetterRoutingKey
	}

	if d.AutoExpire != 0 {
		result["x-expires"] = d.AutoExpire
	}

	if d.MessageTTL != 0 {
		result["x-message-ttl"] = d.MessageTTL
	}

	if d.OverflowStrategy != nil {
		result["x-overflow"] = d.OverflowStrategy.overflowStrategy()
	}

	if d.SingleActiveConsumer {
		result["x-single-active-consumer"] = true
	}

	if d.MaxLength != 0 {
		result["x-max-length"] = d.MaxLength
	}

	if d.DeliveryLimit != 0 {
		result["x-delivery-limit"] = d.DeliveryLimit
	}

	if d.InitialClusterSize != 0 {
		result["x-quorum-initial-group-size"] = d.InitialClusterSize
	}

	if d.TargetClusterSize != 0 {
		result["x-quorum-target-group-size"] = d.TargetClusterSize
	}

	if len(d.DeadLetterStrategy) != 0 {
		result["x-dead-letter-strategy"] = d.DeadLetterStrategy
	}

	if d.LeaderLocator != nil {
		result["x-queue-leader-locator"] = d.LeaderLocator.leaderLocator()
	}

	if len(d.ShovelDestination) != 0 {
		result["x-shovel-destination"] = d.ShovelDestination
		if len(d.ShovelDestinationRoutingKey) != 0 {
			result["x-shovel-destination-key"] = d.ShovelDestinationRoutingKey
		}
		uri := d.ShovelDestinationURI
		if len(uri) == 0 {
			uri = DefaultDelayedShovelDestinationURI
		}
		result["x-shovel-destination-uri"] = uri

		proto := d.ShovelProtocol
		if len(proto) == 0 {
			proto = DefaultDelayedShovelProtocol
		}
		result["x-shovel-protocol"] = proto

		prefetch := d.ShovelPrefetch
		if prefetch == 0 {
			prefetch = DefaultDelayedShovelPrefetch
		}
		result["x-shovel-prefetch-count"] = prefetch

		ack := d.ShovelAcknowledgement
		if len(ack) == 0 {
			ack = DefaultDelayedShovelAcknowledgement
		}
		result["x-shovel-ack-mode"] = ack
	}

	result["x-queue-type"] = string(d.queueType())
	return result
}

func (d *DelayedQueueSpecification) validate(f *featuresAvailable) error {
	if f.isTanzu {
		return nil
	}
	return fmt.Errorf("DelayedQueueSpecification is only supported on Tanzu RabbitMQ 4.x or later")
}

// durationToMaxAge converts a time.Duration to the RabbitMQ stream x-max-age string format.
// RabbitMQ accepts durations expressed as a number followed by a unit: Y, M, D, h, m, s.
// The largest fitting unit is used (e.g. 48h → "2D", 3600s → "1h").
func durationToMaxAge(d time.Duration) string {
	if d == 0 {
		return "0s"
	}
	type unit struct {
		suffix string
		size   time.Duration
	}
	units := []unit{
		{"Y", 365 * 24 * time.Hour},
		{"M", 30 * 24 * time.Hour},
		{"D", 24 * time.Hour},
		{"h", time.Hour},
		{"m", time.Minute},
		{"s", time.Second},
	}
	for _, u := range units {
		if d%u.size == 0 {
			return fmt.Sprintf("%d%s", d/u.size, u.suffix)
		}
	}
	// Fallback: round up to whole seconds for positive durations, enforcing a minimum of 1s.
	if d > 0 {
		secs := int64(d / time.Second)
		if d%time.Second != 0 {
			secs++
		}
		if secs < 1 {
			secs = 1
		}
		return fmt.Sprintf("%ds", secs)
	}
	return fmt.Sprintf("%ds", int64(d.Seconds()))
}

// CustomQueueSpecification represents the specification of a queue with a user-defined queue type.
// It is similar to DefaultQueueSpecification but exposes a QueueTypeName field that is sent to the
// broker as the x-queue-type argument. This allows using any queue type string, including the
// built-in ones ("quorum", "classic", "stream") or custom plugin-provided types.
// When QueueTypeName is empty the x-queue-type argument is omitted and the broker decides the type,
// matching the behaviour of DefaultQueueSpecification.
type CustomQueueSpecification struct {
	// Name is the queue name. Must be unique within the virtual host.
	Name string
	// IsAutoDelete causes the queue to be deleted automatically when the last consumer disconnects.
	IsAutoDelete bool
	// IsExclusive restricts the queue to the connection that declared it and deletes it on disconnection.
	IsExclusive bool
	// QueueTypeName is the value sent as the x-queue-type argument. When empty, the argument is omitted.
	QueueTypeName string
	// AutoExpire is the time in milliseconds after which the queue is deleted if unused (x-expires).
	AutoExpire int64
	// MessageTTL is the default time in milliseconds a message is retained before being discarded (x-message-ttl).
	MessageTTL int64
	// OverflowStrategy controls what happens when the queue reaches MaxLength or MaxLengthBytes (x-overflow).
	OverflowStrategy IOverflowStrategy
	// SingleActiveConsumer ensures only one consumer receives messages at a time (x-single-active-consumer).
	SingleActiveConsumer bool
	// DeadLetterExchange is the exchange to which dead-lettered messages are routed (x-dead-letter-exchange).
	DeadLetterExchange string
	// DeadLetterRoutingKey overrides the routing key used when dead-lettering messages (x-dead-letter-routing-key).
	DeadLetterRoutingKey string
	// MaxLength is the maximum number of messages the queue holds before the overflow strategy is applied (x-max-length).
	MaxLength int64
	// MaxLengthBytes is the maximum total size in bytes of messages in the queue (x-max-length-bytes).
	MaxLengthBytes int64
	// MaxPriority enables priority queuing with the given number of priority levels (x-max-priority).
	MaxPriority int64
	// LeaderLocator controls which cluster node is chosen as the queue leader (x-queue-leader-locator).
	LeaderLocator ILeaderLocator
	// QuorumInitialGroupSize is the initial replication factor for quorum queues (x-quorum-initial-group-size).
	QuorumInitialGroupSize int
	// Arguments holds additional queue arguments passed directly to the broker.
	Arguments map[string]any
}

func (c *CustomQueueSpecification) name() string {
	return c.Name
}

func (c *CustomQueueSpecification) isAutoDelete() bool {
	return c.IsAutoDelete
}

func (c *CustomQueueSpecification) isExclusive() bool {
	return c.IsExclusive
}

func (c *CustomQueueSpecification) queueType() TQueueType {
	return TQueueType(c.QueueTypeName)
}

func (c *CustomQueueSpecification) buildArguments() map[string]any {
	result := c.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if c.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = c.MaxLengthBytes
	}

	if len(c.DeadLetterExchange) != 0 {
		result["x-dead-letter-exchange"] = c.DeadLetterExchange
	}

	if len(c.DeadLetterRoutingKey) != 0 {
		result["x-dead-letter-routing-key"] = c.DeadLetterRoutingKey
	}

	if c.AutoExpire != 0 {
		result["x-expires"] = c.AutoExpire
	}

	if c.MessageTTL != 0 {
		result["x-message-ttl"] = c.MessageTTL
	}

	if c.OverflowStrategy != nil {
		result["x-overflow"] = c.OverflowStrategy.overflowStrategy()
	}

	if c.SingleActiveConsumer {
		result["x-single-active-consumer"] = true
	}

	if c.MaxLength != 0 {
		result["x-max-length"] = c.MaxLength
	}

	if c.MaxPriority != 0 {
		result["x-max-priority"] = c.MaxPriority
	}

	if c.LeaderLocator != nil {
		result["x-queue-leader-locator"] = c.LeaderLocator.leaderLocator()
	}

	if c.QuorumInitialGroupSize != 0 {
		result["x-quorum-initial-group-size"] = c.QuorumInitialGroupSize
	}

	if len(c.QueueTypeName) != 0 {
		result["x-queue-type"] = c.QueueTypeName
	}

	return result
}

func (c *CustomQueueSpecification) validate(*featuresAvailable) error {
	return nil
}

// TExchangeType identifies the routing algorithm used by an exchange.
type TExchangeType string

const (
	// Direct routes messages to queues whose binding key exactly matches the message routing key.
	Direct TExchangeType = "direct"
	// Topic routes messages to queues whose binding pattern matches the message routing key using wildcards (* and #).
	Topic TExchangeType = "topic"
	// FanOut routes messages to all queues bound to the exchange, ignoring the routing key.
	FanOut TExchangeType = "fanout"
	// Headers routes messages based on message header attributes rather than the routing key.
	Headers TExchangeType = "headers"
)

// IExchangeSpecification represents the specification used to declare an exchange.
// The client provides concrete implementations for each standard exchange type as well as
// CustomExchangeSpecification for plugin-provided types.
type IExchangeSpecification interface {
	name() string
	isAutoDelete() bool
	exchangeType() TExchangeType
	arguments() map[string]any
}

// DirectExchangeSpecification represents the specification for a direct exchange.
// Direct exchanges route messages to queues whose binding key exactly matches the routing key.
type DirectExchangeSpecification struct {
	// Name is the exchange name. Must be unique within the virtual host.
	Name string
	// IsAutoDelete causes the exchange to be deleted when the last queue or exchange is unbound from it.
	IsAutoDelete bool
	// Arguments holds additional exchange arguments passed directly to the broker.
	Arguments map[string]any
}

func (d *DirectExchangeSpecification) name() string {
	return d.Name
}

func (d *DirectExchangeSpecification) isAutoDelete() bool {
	return d.IsAutoDelete
}

func (d *DirectExchangeSpecification) exchangeType() TExchangeType {
	return Direct
}

func (d *DirectExchangeSpecification) arguments() map[string]any {
	return d.Arguments
}

// TopicExchangeSpecification represents the specification for a topic exchange.
// Topic exchanges route messages to queues whose binding pattern matches the routing key using wildcards (* and #).
type TopicExchangeSpecification struct {
	// Name is the exchange name. Must be unique within the virtual host.
	Name string
	// IsAutoDelete causes the exchange to be deleted when the last queue or exchange is unbound from it.
	IsAutoDelete bool
	// Arguments holds additional exchange arguments passed directly to the broker.
	Arguments map[string]any
}

func (t *TopicExchangeSpecification) name() string {
	return t.Name
}

func (t *TopicExchangeSpecification) isAutoDelete() bool {
	return t.IsAutoDelete
}

func (t *TopicExchangeSpecification) exchangeType() TExchangeType {
	return Topic
}

func (t *TopicExchangeSpecification) arguments() map[string]any {
	return t.Arguments
}

// FanOutExchangeSpecification represents the specification for a fanout exchange.
// Fanout exchanges broadcast every message to all queues bound to the exchange, ignoring the routing key.
type FanOutExchangeSpecification struct {
	// Name is the exchange name. Must be unique within the virtual host.
	Name string
	// IsAutoDelete causes the exchange to be deleted when the last queue or exchange is unbound from it.
	IsAutoDelete bool
	// Arguments holds additional exchange arguments passed directly to the broker.
	Arguments map[string]any
}

func (f *FanOutExchangeSpecification) name() string {
	return f.Name
}

func (f *FanOutExchangeSpecification) isAutoDelete() bool {
	return f.IsAutoDelete
}

func (f *FanOutExchangeSpecification) exchangeType() TExchangeType {
	return FanOut
}

func (f *FanOutExchangeSpecification) arguments() map[string]any {
	return f.Arguments
}

// HeadersExchangeSpecification represents the specification for a headers exchange.
// Headers exchanges route messages based on header attributes rather than the routing key.
type HeadersExchangeSpecification struct {
	// Name is the exchange name. Must be unique within the virtual host.
	Name string
	// IsAutoDelete causes the exchange to be deleted when the last queue or exchange is unbound from it.
	IsAutoDelete bool
	// Arguments holds additional exchange arguments passed directly to the broker.
	Arguments map[string]any
}

func (h *HeadersExchangeSpecification) name() string {
	return h.Name
}

func (h *HeadersExchangeSpecification) isAutoDelete() bool {
	return h.IsAutoDelete
}

func (h *HeadersExchangeSpecification) exchangeType() TExchangeType {
	return Headers
}

func (h *HeadersExchangeSpecification) arguments() map[string]any {
	return h.Arguments
}

// CustomExchangeSpecification represents the specification for an exchange with a user-defined type.
// Use this when declaring exchanges provided by plugins or when the type string is not one of the
// built-in Direct, Topic, FanOut, or Headers values.
type CustomExchangeSpecification struct {
	// Name is the exchange name. Must be unique within the virtual host.
	Name string
	// IsAutoDelete causes the exchange to be deleted when the last queue or exchange is unbound from it.
	IsAutoDelete bool
	// ExchangeTypeName is the exchange type string sent to the broker (e.g. "x-delayed-message").
	ExchangeTypeName string
	// Arguments holds additional exchange arguments passed directly to the broker.
	Arguments map[string]any
}

func (c *CustomExchangeSpecification) name() string {
	return c.Name
}

func (c *CustomExchangeSpecification) isAutoDelete() bool {
	return c.IsAutoDelete
}

func (c *CustomExchangeSpecification) exchangeType() TExchangeType {
	return TExchangeType(c.ExchangeTypeName)
}

func (c *CustomExchangeSpecification) arguments() map[string]any {
	return c.Arguments
}

// IBindingSpecification represents the specification used to create or delete a binding
// between a source exchange and a destination (queue or exchange).
type IBindingSpecification interface {
	sourceExchange() string
	destination() string
	bindingKey() string
	isDestinationQueue() bool
	arguments() map[string]any
}

// ExchangeToQueueBindingSpecification represents the specification for binding an exchange to a queue.
type ExchangeToQueueBindingSpecification struct {
	// SourceExchange is the name of the exchange that is the source of the binding.
	SourceExchange string
	// DestinationQueue is the name of the queue that receives messages from the source exchange.
	DestinationQueue string
	// BindingKey is the routing key or pattern used to match messages (semantics depend on the exchange type).
	BindingKey string
	// Arguments holds additional binding arguments, such as header-matching criteria for headers exchanges.
	Arguments map[string]any
}

func (e *ExchangeToQueueBindingSpecification) sourceExchange() string {
	return e.SourceExchange
}

func (e *ExchangeToQueueBindingSpecification) destination() string {
	return e.DestinationQueue
}

func (e *ExchangeToQueueBindingSpecification) isDestinationQueue() bool {
	return true
}

func (e *ExchangeToQueueBindingSpecification) bindingKey() string {
	return e.BindingKey
}

func (e *ExchangeToQueueBindingSpecification) arguments() map[string]any {
	return e.Arguments
}

// ExchangeToExchangeBindingSpecification represents the specification for binding one exchange to another.
// This enables exchange-to-exchange routing (E2E bindings).
type ExchangeToExchangeBindingSpecification struct {
	// SourceExchange is the name of the exchange that is the source of the binding.
	SourceExchange string
	// DestinationExchange is the name of the exchange that receives messages from the source exchange.
	DestinationExchange string
	// BindingKey is the routing key or pattern used to match messages (semantics depend on the exchange type).
	BindingKey string
	// Arguments holds additional binding arguments, such as header-matching criteria for headers exchanges.
	Arguments map[string]any
}

func (e *ExchangeToExchangeBindingSpecification) sourceExchange() string {
	return e.SourceExchange
}

func (e *ExchangeToExchangeBindingSpecification) destination() string {
	return e.DestinationExchange
}

func (e *ExchangeToExchangeBindingSpecification) isDestinationQueue() bool {
	return false
}

func (e *ExchangeToExchangeBindingSpecification) bindingKey() string {
	return e.BindingKey
}

func (e *ExchangeToExchangeBindingSpecification) arguments() map[string]any {
	return e.Arguments
}
