package rabbitmqamqp

import (
	"fmt"
	"time"
)

type iEntityIdentifier interface {
	Id() string
}

type TQueueType string

const (
	Quorum  TQueueType = "quorum"
	Classic TQueueType = "classic"
	Stream  TQueueType = "stream"
	Jms     TQueueType = "jms"
	Delayed TQueueType = "delayed"
)

/*
IQueueSpecification represents the specification of a queue.
The implementation of the queue specification can be used to declare a queue with the specified properties and arguments.
The client provides multiple implementations of the queue specification for different use cases,
such as DefaultQueueSpecification, QuorumQueueSpecification, ClassicQueueSpecification, JMSQueueSpecification,
DelayedQueueSpecification, AutoGeneratedQueueSpecification, and CustomQueueSpecification.
The client implementations are helpers that cover the most common use cases, but you can implement your own queue
specification by implementing the IQueueSpecification interface.
*/
type IQueueSpecification interface {
	name() string
	isAutoDelete() bool
	isExclusive() bool
	queueType() TQueueType
	buildArguments() map[string]any
	validate(featuresAvailable *featuresAvailable) error
}

type IOverflowStrategy interface {
	overflowStrategy() string
}

type DropHeadOverflowStrategy struct {
}

func (d *DropHeadOverflowStrategy) overflowStrategy() string {
	return "drop-head"
}

type RejectPublishOverflowStrategy struct {
}

func (r *RejectPublishOverflowStrategy) overflowStrategy() string {
	return "reject-publish"
}

type RejectPublishDlxOverflowStrategy struct {
}

func (r *RejectPublishDlxOverflowStrategy) overflowStrategy() string {
	return "reject-publish-dlx"
}

type ILeaderLocator interface {
	leaderLocator() string
}

type BalancedLeaderLocator struct {
}

func (r *BalancedLeaderLocator) leaderLocator() string {
	return "random"
}

type ClientLocalLeaderLocator struct {
}

func (r *ClientLocalLeaderLocator) leaderLocator() string {
	return "client-local"
}

// DefaultQueueSpecification represents the specification of the default queue.
// It is used when the queue type is not specified.
// The queue type is determined by the server based on the arguments provided per virtual host configuration.
type DefaultQueueSpecification struct {
	Name                   string
	IsAutoDelete           bool
	IsExclusive            bool
	AutoExpire             int64
	MessageTTL             int64
	OverflowStrategy       IOverflowStrategy
	SingleActiveConsumer   bool
	DeadLetterExchange     string
	DeadLetterRoutingKey   string
	MaxLength              int64
	MaxLengthBytes         int64
	MaxPriority            int64
	LeaderLocator          ILeaderLocator
	QuorumInitialGroupSize int
	Arguments              map[string]any
}

func (q *DefaultQueueSpecification) name() string {
	return q.Name
}

func (q *DefaultQueueSpecification) isAutoDelete() bool {
	return q.IsAutoDelete
}

func (q *DefaultQueueSpecification) isExclusive() bool {
	return q.IsExclusive
}

func (q *DefaultQueueSpecification) queueType() TQueueType {
	return ""
}

func (q *DefaultQueueSpecification) buildArguments() map[string]any {
	result := q.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if q.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = q.MaxLengthBytes
	}

	if len(q.DeadLetterExchange) != 0 {
		result["x-dead-letter-exchange"] = q.DeadLetterExchange
	}

	if len(q.DeadLetterRoutingKey) != 0 {
		result["x-dead-letter-routing-key"] = q.DeadLetterRoutingKey
	}

	if q.AutoExpire != 0 {
		result["x-expires"] = q.AutoExpire
	}

	if q.MessageTTL != 0 {
		result["x-message-ttl"] = q.MessageTTL
	}

	if q.OverflowStrategy != nil {
		result["x-overflow"] = q.OverflowStrategy.overflowStrategy()
	}

	if q.SingleActiveConsumer {
		result["x-single-active-consumer"] = true
	}

	if q.MaxLength != 0 {
		result["x-max-length"] = q.MaxLength
	}

	if q.MaxPriority != 0 {
		result["x-max-priority"] = q.MaxPriority
	}

	if q.LeaderLocator != nil {
		result["x-queue-leader-locator"] = q.LeaderLocator.leaderLocator()
	}

	if q.QuorumInitialGroupSize != 0 {
		result["x-quorum-initial-group-size"] = q.QuorumInitialGroupSize
	}

	return result

}

func (q *DefaultQueueSpecification) validate(*featuresAvailable) error {
	return nil
}

/*
	QuorumQueueSpecification represents the specification of the quorum queue
*/

type QuorumQueueSpecification struct {
	Name                   string
	AutoExpire             int64
	MessageTTL             int64
	OverflowStrategy       IOverflowStrategy
	SingleActiveConsumer   bool
	DeadLetterExchange     string
	DeadLetterRoutingKey   string
	MaxLength              int64
	MaxLengthBytes         int64
	DeliveryLimit          int64
	TargetClusterSize      int64
	LeaderLocator          ILeaderLocator
	QuorumInitialGroupSize int
	Arguments              map[string]any
}

func (q *QuorumQueueSpecification) name() string {
	return q.Name
}

func (q *QuorumQueueSpecification) isAutoDelete() bool {
	return false
}

func (q *QuorumQueueSpecification) isExclusive() bool {
	return false
}

func (q *QuorumQueueSpecification) queueType() TQueueType {
	return Quorum
}

func (q *QuorumQueueSpecification) buildArguments() map[string]any {
	result := q.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if q.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = q.MaxLengthBytes
	}

	if len(q.DeadLetterExchange) != 0 {
		result["x-dead-letter-exchange"] = q.DeadLetterExchange
	}

	if len(q.DeadLetterRoutingKey) != 0 {
		result["x-dead-letter-routing-key"] = q.DeadLetterRoutingKey
	}

	if q.AutoExpire != 0 {
		result["x-expires"] = q.AutoExpire
	}

	if q.MessageTTL != 0 {
		result["x-message-ttl"] = q.MessageTTL
	}

	if q.OverflowStrategy != nil {
		result["x-overflow"] = q.OverflowStrategy.overflowStrategy()
	}

	if q.SingleActiveConsumer {
		result["x-single-active-consumer"] = true
	}

	if q.MaxLength != 0 {
		result["x-max-length"] = q.MaxLength
	}

	if q.DeliveryLimit != 0 {
		result["x-delivery-limit"] = q.DeliveryLimit
	}

	if q.TargetClusterSize != 0 {
		result["x-quorum-target-group-size"] = q.TargetClusterSize
	}

	if q.LeaderLocator != nil {
		result["x-queue-leader-locator"] = q.LeaderLocator.leaderLocator()
	}

	if q.QuorumInitialGroupSize != 0 {
		result["x-quorum-initial-group-size"] = q.QuorumInitialGroupSize
	}

	result["x-queue-type"] = string(q.queueType())
	return result
}

func (q *QuorumQueueSpecification) validate(*featuresAvailable) error {
	return nil
}

/*
ClassicQueueSpecification represents the specification of the classic queue
*/
type ClassicQueueSpecification struct {
	Name                 string
	IsAutoDelete         bool
	IsExclusive          bool
	AutoExpire           int64
	MessageTTL           int64
	OverflowStrategy     IOverflowStrategy
	SingleActiveConsumer bool
	DeadLetterExchange   string
	DeadLetterRoutingKey string
	MaxLength            int64
	MaxLengthBytes       int64
	MaxPriority          int64
	LeaderLocator        ILeaderLocator
	Arguments            map[string]any
}

func (q *ClassicQueueSpecification) name() string {
	return q.Name
}

func (q *ClassicQueueSpecification) isAutoDelete() bool {
	return q.IsAutoDelete
}

func (q *ClassicQueueSpecification) isExclusive() bool {
	return q.IsExclusive
}

func (q *ClassicQueueSpecification) queueType() TQueueType {
	return Classic
}

func (q *ClassicQueueSpecification) buildArguments() map[string]any {
	result := q.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if q.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = q.MaxLengthBytes
	}

	if len(q.DeadLetterExchange) != 0 {
		result["x-dead-letter-exchange"] = q.DeadLetterExchange
	}

	if len(q.DeadLetterRoutingKey) != 0 {
		result["x-dead-letter-routing-key"] = q.DeadLetterRoutingKey
	}

	if q.AutoExpire != 0 {
		result["x-expires"] = q.AutoExpire
	}

	if q.MessageTTL != 0 {
		result["x-message-ttl"] = q.MessageTTL
	}

	if q.OverflowStrategy != nil {
		result["x-overflow"] = q.OverflowStrategy.overflowStrategy()
	}

	if q.SingleActiveConsumer {
		result["x-single-active-consumer"] = true
	}

	if q.MaxLength != 0 {
		result["x-max-length"] = q.MaxLength
	}

	if q.MaxPriority != 0 {
		result["x-max-priority"] = q.MaxPriority
	}

	if q.LeaderLocator != nil {
		result["x-queue-leader-locator"] = q.LeaderLocator.leaderLocator()
	}

	result["x-queue-type"] = string(q.queueType())

	return result
}

func (q *ClassicQueueSpecification) validate(*featuresAvailable) error {
	return nil
}

/*
AutoGeneratedQueueSpecification represents the specification of the auto-generated queue.
It is a classic queue with auto-generated name.
It is useful in context like RPC or when you need a temporary queue.
*/
type AutoGeneratedQueueSpecification struct {
	genName        string
	IsAutoDelete   bool
	IsExclusive    bool
	MaxLength      int64
	MaxLengthBytes int64
	Arguments      map[string]any
}

func (a *AutoGeneratedQueueSpecification) name() string {
	if a.genName == "" {
		a.genName = generateNameWithDefaultPrefix()
	}
	return a.genName
}

func (a *AutoGeneratedQueueSpecification) isAutoDelete() bool {
	return a.IsAutoDelete
}

func (a *AutoGeneratedQueueSpecification) isExclusive() bool {
	return a.IsExclusive
}

func (a *AutoGeneratedQueueSpecification) queueType() TQueueType {
	return Classic
}

func (a *AutoGeneratedQueueSpecification) buildArguments() map[string]any {
	result := a.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if a.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = a.MaxLengthBytes
	}

	if a.MaxLength != 0 {
		result["x-max-length"] = a.MaxLength
	}

	result["x-queue-type"] = string(a.queueType())

	return result
}

func (a *AutoGeneratedQueueSpecification) validate(*featuresAvailable) error {
	return nil
}

type StreamQueueSpecification struct {
	Name               string
	MaxLengthBytes     int64
	InitialClusterSize int
	MaxAge             time.Duration
	SegmentSize        int64
	FilterSizeBytes    int64
	Arguments          map[string]any
}

func (s *StreamQueueSpecification) name() string {
	return s.Name
}

func (s *StreamQueueSpecification) isAutoDelete() bool {
	return false
}

func (s *StreamQueueSpecification) isExclusive() bool {
	return false
}

func (s *StreamQueueSpecification) queueType() TQueueType {
	return Stream
}

func (s *StreamQueueSpecification) buildArguments() map[string]any {
	result := s.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if s.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = s.MaxLengthBytes
	}

	if s.InitialClusterSize != 0 {
		result["x-stream-initial-cluster-size"] = s.InitialClusterSize
	}

	if s.MaxAge != 0 {
		result["x-max-age"] = durationToMaxAge(s.MaxAge)
	}

	if s.SegmentSize != 0 {
		result["x-stream-max-segment-size-bytes"] = s.SegmentSize
	}

	if s.FilterSizeBytes != 0 {
		result["x-stream-filter-size-bytes"] = s.FilterSizeBytes
	}

	result["x-queue-type"] = string(s.queueType())

	return result
}

func (s *StreamQueueSpecification) validate(*featuresAvailable) error {
	return nil
}

/*
JMSQueueSpecification represents the specification of a JMS queue (RabbitMQ queue type "jms").
*/
type JMSQueueSpecification struct {
	Name                 string
	Arguments            map[string]any
	AutoExpire           int64
	MessageTTL           int64
	OverflowStrategy     IOverflowStrategy
	DeadLetterExchange   string
	DeadLetterRoutingKey string
	MaxLength            int64
	MaxLengthBytes       int64
	DeliveryLimit        int64
	LeaderLocator        ILeaderLocator
	InitialClusterSize   int
	SelectorFields       []string
}

func (j *JMSQueueSpecification) name() string {
	return j.Name
}

func (j *JMSQueueSpecification) isAutoDelete() bool {
	return false
}

func (j *JMSQueueSpecification) isExclusive() bool {
	return false
}

func (j *JMSQueueSpecification) queueType() TQueueType {
	return Jms
}

func (j *JMSQueueSpecification) buildArguments() map[string]any {
	result := j.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if j.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = j.MaxLengthBytes
	}

	if len(j.DeadLetterExchange) != 0 {
		result["x-dead-letter-exchange"] = j.DeadLetterExchange
	}

	if len(j.DeadLetterRoutingKey) != 0 {
		result["x-dead-letter-routing-key"] = j.DeadLetterRoutingKey
	}

	if j.AutoExpire != 0 {
		result["x-expires"] = j.AutoExpire
	}

	if j.MessageTTL != 0 {
		result["x-message-ttl"] = j.MessageTTL
	}

	if j.OverflowStrategy != nil {
		result["x-overflow"] = j.OverflowStrategy.overflowStrategy()
	}

	result["x-queue-type"] = string(j.queueType())

	return result
}

func (j *JMSQueueSpecification) validate(f *featuresAvailable) error {
	// valid only if it is tanzu
	if f.isTanzu && f.is43rMore {
		return nil
	}
	// error not support for open source RabbitMQ

	return fmt.Errorf("JMSQueueSpecification is only supported on Tanzu RabbitMQ 4.3 or later")

}

// Defaults for optional automatic-shovel arguments when ShovelDestination is set (see Tanzu RabbitMQ delayed queue docs).
const (
	DefaultDelayedShovelDestinationURI  = "amqp://"
	DefaultDelayedShovelProtocol        = "amqp091"
	DefaultDelayedShovelPrefetch        = 50
	DefaultDelayedShovelAcknowledgement = "on-confirm"
)

/*
DelayedQueueSpecification represents the specification of a delayed queue (x-queue-type: delayed).
The management API declares queues as durable; auto-delete defaults to false unless IsAutoDelete is set.
*/
type DelayedQueueSpecification struct {
	Name                 string
	IsAutoDelete         bool
	IsExclusive          bool
	Arguments            map[string]any
	AutoExpire           int64
	MessageTTL           int64
	OverflowStrategy     IOverflowStrategy
	SingleActiveConsumer bool
	DeadLetterExchange   string
	DeadLetterRoutingKey string
	MaxLength            int64
	MaxLengthBytes       int64
	DeliveryLimit        int64
	InitialClusterSize   int
	TargetClusterSize    int64
	DeadLetterStrategy   string
	LeaderLocator        ILeaderLocator

	ShovelDestination           string
	ShovelDestinationRoutingKey string
	ShovelDestinationURI        string
	ShovelProtocol              string
	ShovelPrefetch              int
	ShovelAcknowledgement       string
}

func (d *DelayedQueueSpecification) name() string {
	return d.Name
}

func (d *DelayedQueueSpecification) isAutoDelete() bool {
	return d.IsAutoDelete
}

func (d *DelayedQueueSpecification) isExclusive() bool {
	return d.IsExclusive
}

func (d *DelayedQueueSpecification) queueType() TQueueType {
	return Delayed
}

func (d *DelayedQueueSpecification) buildArguments() map[string]any {
	result := d.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if d.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = d.MaxLengthBytes
	}

	if len(d.DeadLetterExchange) != 0 {
		result["x-dead-letter-exchange"] = d.DeadLetterExchange
	}

	if len(d.DeadLetterRoutingKey) != 0 {
		result["x-dead-letter-routing-key"] = d.DeadLetterRoutingKey
	}

	if d.AutoExpire != 0 {
		result["x-expires"] = d.AutoExpire
	}

	if d.MessageTTL != 0 {
		result["x-message-ttl"] = d.MessageTTL
	}

	if d.OverflowStrategy != nil {
		result["x-overflow"] = d.OverflowStrategy.overflowStrategy()
	}

	if d.SingleActiveConsumer {
		result["x-single-active-consumer"] = true
	}

	if d.MaxLength != 0 {
		result["x-max-length"] = d.MaxLength
	}

	if d.DeliveryLimit != 0 {
		result["x-delivery-limit"] = d.DeliveryLimit
	}

	if d.InitialClusterSize != 0 {
		result["x-quorum-initial-group-size"] = d.InitialClusterSize
	}

	if d.TargetClusterSize != 0 {
		result["x-quorum-target-group-size"] = d.TargetClusterSize
	}

	if len(d.DeadLetterStrategy) != 0 {
		result["x-dead-letter-strategy"] = d.DeadLetterStrategy
	}

	if d.LeaderLocator != nil {
		result["x-queue-leader-locator"] = d.LeaderLocator.leaderLocator()
	}

	if len(d.ShovelDestination) != 0 {
		result["x-shovel-destination"] = d.ShovelDestination
		if len(d.ShovelDestinationRoutingKey) != 0 {
			result["x-shovel-destination-key"] = d.ShovelDestinationRoutingKey
		}
		uri := d.ShovelDestinationURI
		if len(uri) == 0 {
			uri = DefaultDelayedShovelDestinationURI
		}
		result["x-shovel-destination-uri"] = uri

		proto := d.ShovelProtocol
		if len(proto) == 0 {
			proto = DefaultDelayedShovelProtocol
		}
		result["x-shovel-protocol"] = proto

		prefetch := d.ShovelPrefetch
		if prefetch == 0 {
			prefetch = DefaultDelayedShovelPrefetch
		}
		result["x-shovel-prefetch-count"] = prefetch

		ack := d.ShovelAcknowledgement
		if len(ack) == 0 {
			ack = DefaultDelayedShovelAcknowledgement
		}
		result["x-shovel-ack-mode"] = ack
	}

	result["x-queue-type"] = string(d.queueType())
	return result
}

func (d *DelayedQueueSpecification) validate(f *featuresAvailable) error {
	if f.isTanzu {
		return nil
	}
	return fmt.Errorf("DelayedQueueSpecification is only supported on Tanzu RabbitMQ 4.x or later")
}

// durationToMaxAge converts a time.Duration to the RabbitMQ stream x-max-age string format.
// RabbitMQ accepts durations expressed as a number followed by a unit: Y, M, D, h, m, s.
// The largest fitting unit is used (e.g. 48h → "2D", 3600s → "1h").
func durationToMaxAge(d time.Duration) string {
	if d == 0 {
		return "0s"
	}
	type unit struct {
		suffix string
		size   time.Duration
	}
	units := []unit{
		{"Y", 365 * 24 * time.Hour},
		{"M", 30 * 24 * time.Hour},
		{"D", 24 * time.Hour},
		{"h", time.Hour},
		{"m", time.Minute},
		{"s", time.Second},
	}
	for _, u := range units {
		if d%u.size == 0 {
			return fmt.Sprintf("%d%s", d/u.size, u.suffix)
		}
	}
	// Fallback: round up to whole seconds for positive durations, enforcing a minimum of 1s.
	if d > 0 {
		secs := int64(d / time.Second)
		if d%time.Second != 0 {
			secs++
		}
		if secs < 1 {
			secs = 1
		}
		return fmt.Sprintf("%ds", secs)
	}
	return fmt.Sprintf("%ds", int64(d.Seconds()))
}

/*
CustomQueueSpecification represents the specification of a queue with a user-defined queue type.
It is similar to DefaultQueueSpecification but exposes a QueueTypeName field that is sent to the
broker as the x-queue-type argument. This allows using any queue type string, including the
built-in ones ("quorum", "classic", "stream") or custom plugin-provided types ("myQueueType").
When QueueTypeName is empty the x-queue-type argument is omitted and the broker decides the type,
matching the behaviour of DefaultQueueSpecification.
*/
type CustomQueueSpecification struct {
	Name                   string
	IsAutoDelete           bool
	IsExclusive            bool
	QueueTypeName          string
	AutoExpire             int64
	MessageTTL             int64
	OverflowStrategy       IOverflowStrategy
	SingleActiveConsumer   bool
	DeadLetterExchange     string
	DeadLetterRoutingKey   string
	MaxLength              int64
	MaxLengthBytes         int64
	MaxPriority            int64
	LeaderLocator          ILeaderLocator
	QuorumInitialGroupSize int
	Arguments              map[string]any
}

func (c *CustomQueueSpecification) name() string {
	return c.Name
}

func (c *CustomQueueSpecification) isAutoDelete() bool {
	return c.IsAutoDelete
}

func (c *CustomQueueSpecification) isExclusive() bool {
	return c.IsExclusive
}

func (c *CustomQueueSpecification) queueType() TQueueType {
	return TQueueType(c.QueueTypeName)
}

func (c *CustomQueueSpecification) buildArguments() map[string]any {
	result := c.Arguments
	if result == nil {
		result = map[string]any{}
	}

	if c.MaxLengthBytes != 0 {
		result["x-max-length-bytes"] = c.MaxLengthBytes
	}

	if len(c.DeadLetterExchange) != 0 {
		result["x-dead-letter-exchange"] = c.DeadLetterExchange
	}

	if len(c.DeadLetterRoutingKey) != 0 {
		result["x-dead-letter-routing-key"] = c.DeadLetterRoutingKey
	}

	if c.AutoExpire != 0 {
		result["x-expires"] = c.AutoExpire
	}

	if c.MessageTTL != 0 {
		result["x-message-ttl"] = c.MessageTTL
	}

	if c.OverflowStrategy != nil {
		result["x-overflow"] = c.OverflowStrategy.overflowStrategy()
	}

	if c.SingleActiveConsumer {
		result["x-single-active-consumer"] = true
	}

	if c.MaxLength != 0 {
		result["x-max-length"] = c.MaxLength
	}

	if c.MaxPriority != 0 {
		result["x-max-priority"] = c.MaxPriority
	}

	if c.LeaderLocator != nil {
		result["x-queue-leader-locator"] = c.LeaderLocator.leaderLocator()
	}

	if c.QuorumInitialGroupSize != 0 {
		result["x-quorum-initial-group-size"] = c.QuorumInitialGroupSize
	}

	if len(c.QueueTypeName) != 0 {
		result["x-queue-type"] = c.QueueTypeName
	}

	return result
}

func (c *CustomQueueSpecification) validate(*featuresAvailable) error {
	return nil
}

// / **** Exchange ****

// TExchangeType represents the type of exchange
type TExchangeType string

const (
	Direct  TExchangeType = "direct"
	Topic   TExchangeType = "topic"
	FanOut  TExchangeType = "fanout"
	Headers TExchangeType = "headers"
)

// IExchangeSpecification represents the specification of an exchange
type IExchangeSpecification interface {
	name() string
	isAutoDelete() bool
	exchangeType() TExchangeType
	arguments() map[string]any
}

type DirectExchangeSpecification struct {
	Name         string
	IsAutoDelete bool
	Arguments    map[string]any
}

func (d *DirectExchangeSpecification) name() string {
	return d.Name
}

func (d *DirectExchangeSpecification) isAutoDelete() bool {
	return d.IsAutoDelete
}

func (d *DirectExchangeSpecification) exchangeType() TExchangeType {
	return Direct
}

func (d *DirectExchangeSpecification) arguments() map[string]any {
	return d.Arguments
}

type TopicExchangeSpecification struct {
	Name         string
	IsAutoDelete bool
	Arguments    map[string]any
}

func (t *TopicExchangeSpecification) name() string {
	return t.Name
}

func (t *TopicExchangeSpecification) isAutoDelete() bool {
	return t.IsAutoDelete
}

func (t *TopicExchangeSpecification) exchangeType() TExchangeType {
	return Topic
}

func (t *TopicExchangeSpecification) arguments() map[string]any {
	return t.Arguments
}

type FanOutExchangeSpecification struct {
	Name         string
	IsAutoDelete bool
	Arguments    map[string]any
}

func (f *FanOutExchangeSpecification) name() string {
	return f.Name
}

func (f *FanOutExchangeSpecification) isAutoDelete() bool {
	return f.IsAutoDelete
}

func (f *FanOutExchangeSpecification) exchangeType() TExchangeType {
	return FanOut
}

func (f *FanOutExchangeSpecification) arguments() map[string]any {
	return f.Arguments
}

type HeadersExchangeSpecification struct {
	Name         string
	IsAutoDelete bool
	Arguments    map[string]any
}

func (h *HeadersExchangeSpecification) name() string {
	return h.Name
}

func (h *HeadersExchangeSpecification) isAutoDelete() bool {
	return h.IsAutoDelete
}

func (h *HeadersExchangeSpecification) exchangeType() TExchangeType {
	return Headers
}

func (h *HeadersExchangeSpecification) arguments() map[string]any {
	return h.Arguments
}

type CustomExchangeSpecification struct {
	Name             string
	IsAutoDelete     bool
	ExchangeTypeName string
	Arguments        map[string]any
}

func (c *CustomExchangeSpecification) name() string {
	return c.Name
}

func (c *CustomExchangeSpecification) isAutoDelete() bool {
	return c.IsAutoDelete
}

func (c *CustomExchangeSpecification) exchangeType() TExchangeType {
	return TExchangeType(c.ExchangeTypeName)
}

func (c *CustomExchangeSpecification) arguments() map[string]any {
	return c.Arguments
}

// / **** Binding ****

type IBindingSpecification interface {
	sourceExchange() string
	destination() string
	bindingKey() string
	isDestinationQueue() bool
	arguments() map[string]any
}

type ExchangeToQueueBindingSpecification struct {
	SourceExchange   string
	DestinationQueue string
	BindingKey       string
	Arguments        map[string]any
}

func (e *ExchangeToQueueBindingSpecification) sourceExchange() string {
	return e.SourceExchange
}

func (e *ExchangeToQueueBindingSpecification) destination() string {
	return e.DestinationQueue
}

func (e *ExchangeToQueueBindingSpecification) isDestinationQueue() bool {
	return true
}

func (e *ExchangeToQueueBindingSpecification) bindingKey() string {
	return e.BindingKey
}

func (e *ExchangeToQueueBindingSpecification) arguments() map[string]any {
	return e.Arguments
}

type ExchangeToExchangeBindingSpecification struct {
	SourceExchange      string
	DestinationExchange string
	BindingKey          string
	Arguments           map[string]any
}

func (e *ExchangeToExchangeBindingSpecification) sourceExchange() string {
	return e.SourceExchange
}

func (e *ExchangeToExchangeBindingSpecification) destination() string {
	return e.DestinationExchange
}

func (e *ExchangeToExchangeBindingSpecification) isDestinationQueue() bool {
	return false
}

func (e *ExchangeToExchangeBindingSpecification) bindingKey() string {
	return e.BindingKey
}

func (e *ExchangeToExchangeBindingSpecification) arguments() map[string]any {
	return e.Arguments
}
