package rabbitmqamqp

import (
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("Entities", func() {
	Describe("AutoGeneratedQueueSpecification", func() {
		It("should generate a unique name consistently", func() {
			queue := &AutoGeneratedQueueSpecification{}
			generatedName := queue.name()
			Expect(queue.name()).To(Equal(generatedName), "same instance should generate the same name")

			anotherQueue := &AutoGeneratedQueueSpecification{}
			anotherGeneratedName := anotherQueue.name()
			Expect(anotherQueue.name()).To(Equal(anotherGeneratedName), "same instance should generate the same name")

			Expect(generatedName).ToNot(Equal(anotherGeneratedName), "different instances should generate different names")
		})
	})

	Describe("StreamQueueSpecification", func() {
		It("should set x-stream-max-segment-size-bytes when StreamMaxSegmentSize is set", func() {
			spec := &StreamQueueSpecification{
				Name:                 "my-stream",
				StreamMaxSegmentSize: 500_000_000,
			}
			args := spec.buildArguments()
			Expect(args["x-stream-max-segment-size-bytes"]).To(Equal(500_000_000))
		})

		It("should not set x-stream-max-segment-size-bytes when StreamMaxSegmentSize is zero", func() {
			spec := &StreamQueueSpecification{Name: "my-stream"}
			args := spec.buildArguments()
			Expect(args).ToNot(HaveKey("x-stream-max-segment-size-bytes"))
		})

		It("should set x-max-age when MaxAge is set", func() {
			spec := &StreamQueueSpecification{
				Name:   "my-stream",
				MaxAge: 7 * 24 * time.Hour,
			}
			args := spec.buildArguments()
			Expect(args["x-max-age"]).To(Equal("7D"))
		})

		It("should not set x-max-age when MaxAge is zero", func() {
			spec := &StreamQueueSpecification{Name: "my-stream"}
			args := spec.buildArguments()
			Expect(args).ToNot(HaveKey("x-max-age"))
		})

		It("should set both x-max-age and x-stream-max-segment-size-bytes together", func() {
			spec := &StreamQueueSpecification{
				Name:                 "my-stream",
				MaxAge:               30 * 24 * time.Hour,
				StreamMaxSegmentSize: 100_000_000,
			}
			args := spec.buildArguments()
			Expect(args["x-max-age"]).To(Equal("1M"))
			Expect(args["x-stream-max-segment-size-bytes"]).To(Equal(100_000_000))
		})

		It("should always set x-queue-type to stream", func() {
			spec := &StreamQueueSpecification{Name: "my-stream"}
			args := spec.buildArguments()
			Expect(args["x-queue-type"]).To(Equal("stream"))
		})
	})

	Describe("durationToMaxAge", func() {
		DescribeTable("converts duration to RabbitMQ max-age string",
			func(d time.Duration, expected string) {
				Expect(durationToMaxAge(d)).To(Equal(expected))
			},
			Entry("seconds", 30*time.Second, "30s"),
			Entry("minutes", 5*time.Minute, "5m"),
			Entry("hours", 2*time.Hour, "2h"),
			Entry("days", 3*24*time.Hour, "3D"),
			Entry("months (30 days)", 30*24*time.Hour, "1M"),
			Entry("years (365 days)", 365*24*time.Hour, "1Y"),
			Entry("zero", time.Duration(0), "0s"),
		)
	})
})
