package rabbitmqamqp

import (
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("Entities", func() {
	Describe("AutoGeneratedQueueSpecification", func() {
		It("should generate a unique name consistently", func() {
			queue := &AutoGeneratedQueueSpecification{}
			generatedName := queue.name()
			Expect(queue.name()).To(Equal(generatedName), "same instance should generate the same name")

			anotherQueue := &AutoGeneratedQueueSpecification{}
			anotherGeneratedName := anotherQueue.name()
			Expect(anotherQueue.name()).To(Equal(anotherGeneratedName), "same instance should generate the same name")

			Expect(generatedName).ToNot(Equal(anotherGeneratedName), "different instances should generate different names")
		})
	})

	Describe("StreamQueueSpecification", func() {
		It("should set x-stream-max-segment-size-bytes when SegmentSize is set", func() {
			spec := &StreamQueueSpecification{
				Name:        "my-stream",
				SegmentSize: 500_000_000,
			}
			args := spec.buildArguments()
			Expect(args["x-stream-max-segment-size-bytes"]).To(Equal(int64(500_000_000)))
		})

		It("should not set x-stream-max-segment-size-bytes when SegmentSize is zero", func() {
			spec := &StreamQueueSpecification{Name: "my-stream"}
			args := spec.buildArguments()
			Expect(args).ToNot(HaveKey("x-stream-max-segment-size-bytes"))
		})

		It("should set x-max-age when MaxAge is set", func() {
			spec := &StreamQueueSpecification{
				Name:   "my-stream",
				MaxAge: 7 * 24 * time.Hour,
			}
			args := spec.buildArguments()
			Expect(args["x-max-age"]).To(Equal("7D"))
		})

		It("should not set x-max-age when MaxAge is zero", func() {
			spec := &StreamQueueSpecification{Name: "my-stream"}
			args := spec.buildArguments()
			Expect(args).ToNot(HaveKey("x-max-age"))
		})

		It("should set both x-max-age and x-stream-max-segment-size-bytes together", func() {
			spec := &StreamQueueSpecification{
				Name:        "my-stream",
				MaxAge:      30 * 24 * time.Hour,
				SegmentSize: 100_000_000,
			}
			args := spec.buildArguments()
			Expect(args["x-max-age"]).To(Equal("1M"))
			Expect(args["x-stream-max-segment-size-bytes"]).To(Equal(int64(100_000_000)))
		})

		It("should set x-stream-filter-size-bytes when FilterSizeBytes is set", func() {
			spec := &StreamQueueSpecification{
				Name:            "my-stream",
				FilterSizeBytes: 16,
			}
			args := spec.buildArguments()
			Expect(args["x-stream-filter-size-bytes"]).To(Equal(int64(16)))
		})

		It("should not set x-stream-filter-size-bytes when FilterSizeBytes is zero", func() {
			spec := &StreamQueueSpecification{Name: "my-stream"}
			args := spec.buildArguments()
			Expect(args).ToNot(HaveKey("x-stream-filter-size-bytes"))
		})

		It("should always set x-queue-type to stream", func() {
			spec := &StreamQueueSpecification{Name: "my-stream"}
			args := spec.buildArguments()
			Expect(args["x-queue-type"]).To(Equal("stream"))
		})
	})

	Describe("JMSQueueSpecification", func() {
		It("should always set x-queue-type to jms and fixed durability flags", func() {
			spec := &JMSQueueSpecification{Name: "my-jms-queue"}
			Expect(spec.isAutoDelete()).To(BeFalse())
			Expect(spec.isExclusive()).To(BeFalse())
			Expect(spec.queueType()).To(Equal(Jms))
			args := spec.buildArguments()
			Expect(args["x-queue-type"]).To(Equal("jms"))
		})

		It("should merge optional arguments", func() {
			spec := &JMSQueueSpecification{
				Name:      "my-jms-queue",
				Arguments: map[string]any{"x-max-length-bytes": int64(1000)},
			}
			args := spec.buildArguments()
			Expect(args["x-max-length-bytes"]).To(Equal(int64(1000)))
			Expect(args["x-queue-type"]).To(Equal("jms"))
		})
	})

	Describe("DelayedQueueSpecification", func() {
		It("should set x-queue-type to delayed and default durability-related flags", func() {
			spec := &DelayedQueueSpecification{Name: "my-delayed-queue"}
			Expect(spec.isAutoDelete()).To(BeFalse())
			Expect(spec.isExclusive()).To(BeFalse())
			Expect(spec.queueType()).To(Equal(Delayed))
			args := spec.buildArguments()
			Expect(args["x-queue-type"]).To(Equal("delayed"))
		})

		It("should map standard and quorum-style arguments", func() {
			spec := &DelayedQueueSpecification{
				Name:                 "dq",
				AutoExpire:           60000,
				MessageTTL:           30000,
				SingleActiveConsumer: true,
				DeadLetterExchange:   "dlx",
				DeadLetterRoutingKey: "rk",
				MaxLength:            100,
				MaxLengthBytes:       2000,
				DeliveryLimit:        5,
				InitialClusterSize:   3,
				TargetClusterSize:    5,
				DeadLetterStrategy:   "at-least-once",
				LeaderLocator:        &ClientLocalLeaderLocator{},
				OverflowStrategy:     &RejectPublishOverflowStrategy{},
			}
			args := spec.buildArguments()
			Expect(args["x-expires"]).To(Equal(int64(60000)))
			Expect(args["x-message-ttl"]).To(Equal(int64(30000)))
			Expect(args["x-single-active-consumer"]).To(BeTrue())
			Expect(args["x-dead-letter-exchange"]).To(Equal("dlx"))
			Expect(args["x-dead-letter-routing-key"]).To(Equal("rk"))
			Expect(args["x-max-length"]).To(Equal(int64(100)))
			Expect(args["x-max-length-bytes"]).To(Equal(int64(2000)))
			Expect(args["x-delivery-limit"]).To(Equal(int64(5)))
			Expect(args["x-quorum-initial-group-size"]).To(Equal(3))
			Expect(args["x-quorum-target-group-size"]).To(Equal(int64(5)))
			Expect(args["x-dead-letter-strategy"]).To(Equal("at-least-once"))
			Expect(args["x-queue-leader-locator"]).To(Equal("client-local"))
			Expect(args["x-overflow"]).To(Equal("reject-publish"))
			Expect(args["x-queue-type"]).To(Equal("delayed"))
		})

		It("should set automatic shovel arguments with defaults when ShovelDestination is set", func() {
			spec := &DelayedQueueSpecification{
				Name:                  "dq",
				ShovelDestination:     "dest-exch",
				ShovelPrefetch:        100,
				ShovelProtocol:        "amqp10",
				ShovelAcknowledgement: "no-ack",
			}
			args := spec.buildArguments()
			Expect(args["x-shovel-destination"]).To(Equal("dest-exch"))
			Expect(args["x-shovel-destination-uri"]).To(Equal(DefaultDelayedShovelDestinationURI))
			Expect(args["x-shovel-protocol"]).To(Equal("amqp10"))
			Expect(args["x-shovel-prefetch-count"]).To(Equal(100))
			Expect(args["x-shovel-ack-mode"]).To(Equal("no-ack"))
		})

		It("should apply default shovel prefetch, protocol, ack, and URI when only destination is set", func() {
			spec := &DelayedQueueSpecification{
				Name:              "dq",
				ShovelDestination: "ex",
			}
			args := spec.buildArguments()
			Expect(args["x-shovel-prefetch-count"]).To(Equal(DefaultDelayedShovelPrefetch))
			Expect(args["x-shovel-protocol"]).To(Equal(DefaultDelayedShovelProtocol))
			Expect(args["x-shovel-ack-mode"]).To(Equal(DefaultDelayedShovelAcknowledgement))
			Expect(args["x-shovel-destination-uri"]).To(Equal(DefaultDelayedShovelDestinationURI))
		})

		It("should set x-shovel-destination-key when set", func() {
			spec := &DelayedQueueSpecification{
				Name:                        "dq",
				ShovelDestination:           "ex",
				ShovelDestinationRoutingKey: "orders.key",
			}
			args := spec.buildArguments()
			Expect(args["x-shovel-destination-key"]).To(Equal("orders.key"))
		})
	})

	Describe("CustomQueueSpecification", func() {
		It("should set x-queue-type to the custom string when QueueTypeName is non-empty", func() {
			spec := &CustomQueueSpecification{
				Name:          "my-custom-queue",
				QueueTypeName: "quorum",
			}
			Expect(spec.queueType()).To(Equal(TQueueType("quorum")))
			args := spec.buildArguments()
			Expect(args["x-queue-type"]).To(Equal("quorum"))
		})

		It("should omit x-queue-type when QueueTypeName is empty", func() {
			spec := &CustomQueueSpecification{Name: "my-queue"}
			args := spec.buildArguments()
			Expect(args).ToNot(HaveKey("x-queue-type"))
		})

		It("should reflect IsAutoDelete and IsExclusive fields", func() {
			spec := &CustomQueueSpecification{
				Name:         "my-queue",
				IsAutoDelete: true,
				IsExclusive:  true,
			}
			Expect(spec.isAutoDelete()).To(BeTrue())
			Expect(spec.isExclusive()).To(BeTrue())

			spec2 := &CustomQueueSpecification{Name: "my-queue"}
			Expect(spec2.isAutoDelete()).To(BeFalse())
			Expect(spec2.isExclusive()).To(BeFalse())
		})

		It("should map all DefaultQueueSpecification-style arguments", func() {
			spec := &CustomQueueSpecification{
				Name:                   "my-custom-queue",
				QueueTypeName:          "quorum",
				AutoExpire:             60000,
				MessageTTL:             30000,
				OverflowStrategy:       &RejectPublishOverflowStrategy{},
				SingleActiveConsumer:   true,
				DeadLetterExchange:     "dlx",
				DeadLetterRoutingKey:   "dlx-rk",
				MaxLength:              500,
				MaxLengthBytes:         1_000_000,
				MaxPriority:            5,
				LeaderLocator:          &ClientLocalLeaderLocator{},
				QuorumInitialGroupSize: 3,
			}
			args := spec.buildArguments()
			Expect(args["x-queue-type"]).To(Equal("quorum"))
			Expect(args["x-expires"]).To(Equal(int64(60000)))
			Expect(args["x-message-ttl"]).To(Equal(int64(30000)))
			Expect(args["x-overflow"]).To(Equal("reject-publish"))
			Expect(args["x-single-active-consumer"]).To(BeTrue())
			Expect(args["x-dead-letter-exchange"]).To(Equal("dlx"))
			Expect(args["x-dead-letter-routing-key"]).To(Equal("dlx-rk"))
			Expect(args["x-max-length"]).To(Equal(int64(500)))
			Expect(args["x-max-length-bytes"]).To(Equal(int64(1_000_000)))
			Expect(args["x-max-priority"]).To(Equal(int64(5)))
			Expect(args["x-queue-leader-locator"]).To(Equal("client-local"))
			Expect(args["x-quorum-initial-group-size"]).To(Equal(3))
		})

		It("should merge extra Arguments with built arguments", func() {
			spec := &CustomQueueSpecification{
				Name:          "my-custom-queue",
				QueueTypeName: "quorum",
				Arguments:     map[string]any{"custom-key": "custom-value"},
			}
			args := spec.buildArguments()
			Expect(args["x-queue-type"]).To(Equal("quorum"))
			Expect(args["custom-key"]).To(Equal("custom-value"))
		})

		It("should accept any arbitrary queue type string", func() {
			spec := &CustomQueueSpecification{
				Name:          "my-plugin-queue",
				QueueTypeName: "myQueueType",
			}
			Expect(spec.queueType()).To(Equal(TQueueType("myQueueType")))
			args := spec.buildArguments()
			Expect(args["x-queue-type"]).To(Equal("myQueueType"))
		})

		It("should always pass validation", func() {
			spec := &CustomQueueSpecification{
				Name:          "my-custom-queue",
				QueueTypeName: "quorum",
			}
			Expect(spec.validate(nil)).To(BeNil())
		})
	})

	Describe("QuorumQueueSpecification delayed retry", func() {
		It("should set x-delayed-retry-type when DelayedRetryType is set", func() {
			spec := &QuorumQueueSpecification{
				Name:             "my-qq",
				DelayedRetryType: QuorumQueueDelayedRetryReturned,
			}
			args := spec.buildArguments()
			Expect(args["x-delayed-retry-type"]).To(Equal("returned"))
		})

		It("should set x-delayed-retry-type to disabled", func() {
			spec := &QuorumQueueSpecification{
				Name:             "my-qq",
				DelayedRetryType: QuorumQueueDelayedRetryDisabled,
			}
			args := spec.buildArguments()
			Expect(args["x-delayed-retry-type"]).To(Equal("disabled"))
		})

		It("should not set x-delayed-retry-type when DelayedRetryType is empty", func() {
			spec := &QuorumQueueSpecification{Name: "my-qq"}
			args := spec.buildArguments()
			Expect(args).ToNot(HaveKey("x-delayed-retry-type"))
		})

		It("should set x-delayed-retry-min in milliseconds when DelayedRetryMin is set", func() {
			spec := &QuorumQueueSpecification{
				Name:            "my-qq",
				DelayedRetryMin: 5 * time.Second,
			}
			args := spec.buildArguments()
			Expect(args["x-delayed-retry-min"]).To(Equal(int64(5000)))
		})

		It("should not set x-delayed-retry-min when DelayedRetryMin is zero", func() {
			spec := &QuorumQueueSpecification{Name: "my-qq"}
			args := spec.buildArguments()
			Expect(args).ToNot(HaveKey("x-delayed-retry-min"))
		})

		It("should set x-delayed-retry-max in milliseconds when DelayedRetryMax is set", func() {
			spec := &QuorumQueueSpecification{
				Name:            "my-qq",
				DelayedRetryMax: 30 * time.Second,
			}
			args := spec.buildArguments()
			Expect(args["x-delayed-retry-max"]).To(Equal(int64(30000)))
		})

		It("should not set x-delayed-retry-max when DelayedRetryMax is zero", func() {
			spec := &QuorumQueueSpecification{Name: "my-qq"}
			args := spec.buildArguments()
			Expect(args).ToNot(HaveKey("x-delayed-retry-max"))
		})

		It("should set all three delayed retry arguments together", func() {
			spec := &QuorumQueueSpecification{
				Name:             "my-qq",
				DelayedRetryType: QuorumQueueDelayedRetryReturned,
				DelayedRetryMin:  2 * time.Second,
				DelayedRetryMax:  60 * time.Second,
			}
			args := spec.buildArguments()
			Expect(args["x-delayed-retry-type"]).To(Equal("returned"))
			Expect(args["x-delayed-retry-min"]).To(Equal(int64(2000)))
			Expect(args["x-delayed-retry-max"]).To(Equal(int64(60000)))
			Expect(args["x-queue-type"]).To(Equal("quorum"))
		})

		It("should fail validation when delayed retry fields are set on RabbitMQ < 4.3", func() {
			spec := &QuorumQueueSpecification{
				Name:             "my-qq",
				DelayedRetryType: QuorumQueueDelayedRetryReturned,
			}
			err := spec.validate(&featuresAvailable{is43rMore: false})
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring("4.3"))
		})

		It("should pass validation when delayed retry fields are set on RabbitMQ >= 4.3", func() {
			spec := &QuorumQueueSpecification{
				Name:             "my-qq",
				DelayedRetryType: QuorumQueueDelayedRetryReturned,
				DelayedRetryMin:  2 * time.Second,
				DelayedRetryMax:  60 * time.Second,
			}
			Expect(spec.validate(&featuresAvailable{is43rMore: true})).To(BeNil())
		})

		It("should pass validation when no delayed retry fields are set regardless of version", func() {
			spec := &QuorumQueueSpecification{Name: "my-qq"}
			Expect(spec.validate(&featuresAvailable{is43rMore: false})).To(BeNil())
			Expect(spec.validate(&featuresAvailable{is43rMore: true})).To(BeNil())
			Expect(spec.validate(nil)).To(BeNil())
		})

		DescribeTable("should map each QuorumQueueDelayedRetryType to the correct wire value",
			func(retryType QuorumQueueDelayedRetryType, expected string) {
				spec := &QuorumQueueSpecification{
					Name:             "my-qq",
					DelayedRetryType: retryType,
				}
				Expect(spec.buildArguments()["x-delayed-retry-type"]).To(Equal(expected))
			},
			Entry("Disabled", QuorumQueueDelayedRetryDisabled, "disabled"),
			Entry("All", QuorumQueueDelayedRetryAll, "all"),
			Entry("Failed", QuorumQueueDelayedRetryFailed, "failed"),
			Entry("Returned", QuorumQueueDelayedRetryReturned, "returned"),
		)

		DescribeTable("should fail validation when any DelayedRetryType is set on RabbitMQ < 4.3",
			func(retryType QuorumQueueDelayedRetryType) {
				spec := &QuorumQueueSpecification{
					Name:             "my-qq",
					DelayedRetryType: retryType,
				}
				err := spec.validate(&featuresAvailable{is43rMore: false})
				Expect(err).To(HaveOccurred())
				Expect(err.Error()).To(ContainSubstring("4.3"))
			},
			Entry("Disabled", QuorumQueueDelayedRetryDisabled),
			Entry("All", QuorumQueueDelayedRetryAll),
			Entry("Failed", QuorumQueueDelayedRetryFailed),
			Entry("Returned", QuorumQueueDelayedRetryReturned),
		)

		DescribeTable("should pass validation when any DelayedRetryType is set on RabbitMQ >= 4.3",
			func(retryType QuorumQueueDelayedRetryType) {
				spec := &QuorumQueueSpecification{
					Name:             "my-qq",
					DelayedRetryType: retryType,
				}
				Expect(spec.validate(&featuresAvailable{is43rMore: true})).To(BeNil())
			},
			Entry("Disabled", QuorumQueueDelayedRetryDisabled),
			Entry("All", QuorumQueueDelayedRetryAll),
			Entry("Failed", QuorumQueueDelayedRetryFailed),
			Entry("Returned", QuorumQueueDelayedRetryReturned),
		)
	})

	Describe("durationToMaxAge", func() {
		DescribeTable("converts duration to RabbitMQ max-age string",
			func(d time.Duration, expected string) {
				Expect(durationToMaxAge(d)).To(Equal(expected))
			},
			Entry("seconds", 30*time.Second, "30s"),
			Entry("minutes", 5*time.Minute, "5m"),
			Entry("hours", 2*time.Hour, "2h"),
			Entry("days", 3*24*time.Hour, "3D"),
			Entry("months (30 days)", 30*24*time.Hour, "1M"),
			Entry("years (365 days)", 365*24*time.Hour, "1Y"),
			Entry("zero", time.Duration(0), "0s"),
		)
	})
})
