name: Test against supported go-version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
        - stable
        - oldstable
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        id: setup_go
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Start RabbitMQ
        id: start-rabbitmq
        run: ${{ github.workspace }}/.ci/ubuntu/gha-setup.sh
      - name: Test
        timeout-minutes: 15
        run: make test
      - name: Check for errors in RabbitMQ logs
        run: ${{ github.workspace}}/.ci/ubuntu/gha-log-check.sh
      - name: Maybe upload RabbitMQ logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: rabbitmq-logs-integration-ubuntu
          path: ${{ github.workspace }}/.ci/ubuntu/log/
